/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller220 */

#ifndef _Included_azertia_jni_Caller220
#define _Included_azertia_jni_Caller220
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__IZ
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMemNull
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMemNull
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
