/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller22220 */

#ifndef _Included_azertia_jni_Caller22220
#define _Included_azertia_jni_Caller22220
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller22220
 * Method:    printGlobalMemories
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller22220_printGlobalMemories
  (JNIEnv *, jclass);

/*
 * Class:     azertia_jni_Caller22220
 * Method:    saveStatusToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller22220_saveStatusToFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller22220
 * Method:    loadStatusFromFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller22220_loadStatusFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller22220
 * Method:    globalMemories2Str
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_azertia_jni_Caller22220_globalMemories2Str
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
