/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller220 */

#ifndef _Included_azertia_jni_Caller220
#define _Included_azertia_jni_Caller220
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMem
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMem__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMemAddress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMemAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     azertia_jni_Caller220
 * Method:    ACputMemNull
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller220_ACputMemNull
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
