/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller20 */

#ifndef _Included_azertia_jni_Caller20
#define _Included_azertia_jni_Caller20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller20
 * Method:    memAlloc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_azertia_jni_Caller20_memAlloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     azertia_jni_Caller20
 * Method:    memFree
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller20_memFree
  (JNIEnv *, jclass, jint);

/*
 * Class:     azertia_jni_Caller20
 * Method:    destroyScript
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller20_destroyScript
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
