/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller */

#ifndef _Included_azertia_jni_Caller
#define _Included_azertia_jni_Caller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller_init
  (JNIEnv *, jclass);

/*
 * Class:     azertia_jni_Caller
 * Method:    loadScript
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller_loadScript
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller
 * Method:    insertScript
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller_insertScript
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller_flush
  (JNIEnv *, jclass);

/*
 * Class:     azertia_jni_Caller
 * Method:    namespaceForHint
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_azertia_jni_Caller_namespaceForHint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller
 * Method:    call
 * Signature: (I[J)J
 */
JNIEXPORT jlong JNICALL Java_azertia_jni_Caller_call
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_azertia_jni_Caller_getMemType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_azertia_jni_Caller_getMemStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_azertia_jni_Caller_getMemFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_azertia_jni_Caller_getMemDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_azertia_jni_Caller_getMemBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_azertia_jni_Caller_getMemInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     azertia_jni_Caller
 * Method:    getMemAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_azertia_jni_Caller_getMemAddress
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
