/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class azertia_jni_Caller2220 */

#ifndef _Included_azertia_jni_Caller2220
#define _Included_azertia_jni_Caller2220
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     azertia_jni_Caller2220
 * Method:    bindNamespace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller2220_bindNamespace
  (JNIEnv *, jclass, jint);

/*
 * Class:     azertia_jni_Caller2220
 * Method:    unbindNamespace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller2220_unbindNamespace
  (JNIEnv *, jclass, jint);

/*
 * Class:     azertia_jni_Caller2220
 * Method:    addTrustedPublicKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller2220_addTrustedPublicKey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     azertia_jni_Caller2220
 * Method:    clearTrustedPublicKeys
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_azertia_jni_Caller2220_clearTrustedPublicKeys
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
