plugins {
    id 'application'
}
application { mainClass = 'azertia.Main' }
dependencies {
    implementation project(':abdJava')
    implementation 'com.google.code.gson:gson:2.11.0'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test { useJUnitPlatform() }
